apiVersion: batch/v1
kind: Job
metadata:
  name: as-jet-train-job
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: as-train-pvc
          persistentVolumeClaim:
            claimName: as-jet-training-pvc

      containers:
        - name: train
          image: python:3.10-slim
          command:
            - /bin/bash
            - -c
            - |
              set -e  # fail on any error

              echo "=== Environment setup complete, starting training ==="
              export CUDA_LAUNCH_BLOCKING=1
              export TORCH_USE_CUDA_DSA=1

              source /mnt/data/python-env/bin/activate
              cd /mnt/data/src
              python3 train.py --batch_size=25 --num_epochs=50 --n_samples=50000 --n_layers=6
          volumeMounts:
            - mountPath: /mnt/data
              name: as-train-pvc
          resources:
            limits:
              nvidia.com/gpu: 1
              memory: "16Gi"
              cpu: "2.4"
            requests:
              nvidia.com/gpu: 1
              memory: "16Gi"
              cpu: "2"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                      - gpn-fiona-mizzou-2.rnet.missouri.edu
                      - rci-nrp-gpu-05.sdsu.edu
                      - node-2-2.sdsc.optiputer.net
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-GeForce-RTX-4090
                - NVIDIA-GeForce-RTX-3090
                - NVIDIA-A10
                - NVIDIA-TITAN-RTX
                - NVIDIA-RTX-A5000