apiVersion: v1
kind: Pod
metadata:
  name: as-jet-debug-pod
spec:
  restartPolicy: Never
  volumes:
    - name: as-train-pvc
      persistentVolumeClaim:
        claimName: as-jet-train-pvc
  initContainers:
  - name: setup-env
    image: python:3.10-slim
    volumeMounts:
      - mountPath: /mnt/data
        name: as-train-pvc
    command:
      - /bin/bash
      - -c
      - |
        mkdir -p /mnt/data
        ls -la /mnt/data

  containers:
  - name: debug
    image: python:3.10-slim
    command:
      - /bin/bash
      - -c
      - |
        echo "=== Checking persistent volume contents ==="
        ls -la /mnt/data/
        
        echo "=== Activating existing environment ==="
        source /mnt/data/python-env/bin/activate
        
        # Install Jupyter in existing environment
        pip install jupyter ipython
        
        # Set debugging environment variables
        
        
        echo "Run: kubectl port-forward as-jet-debug-pod 8888:8888"
        apt update -y && apt install ffmpeg -y
        
        # Start Jupyter
        cd /mnt/data/
        jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
        
    ports:
    - containerPort: 8888
    volumeMounts:
      - mountPath: /mnt/data
        name: as-train-pvc
    resources:
      limits:
        nvidia.com/gpu: 1
        memory: "16Gi"
        cpu: "2.4"
      requests:
        nvidia.com/gpu: 1
        memory: "16Gi"
        cpu: "2"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
                  - gpn-fiona-mizzou-2.rnet.missouri.edu
                  - rci-nrp-gpu-05.sdsu.edu
                  - node-2-2.sdsc.optiputer.net
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-GeForce-RTX-4090
            - NVIDIA-GeForce-RTX-3090
            - NVIDIA-A10
            - NVIDIA-TITAN-RTX
            - NVIDIA-RTX-A5000