data:
  num_particles: 30

model:
  n_layers: 5
  use_residual: true
  use_hyperbolic: true

training:
  train_space: polar
  time_sampling: power_law
  batch_size: 64
  num_epochs: 300
  use_cosine_lr: true
  use_time_sampling: true
  use_curriculum: false

inference:
  n_samples: 100000
  integration_steps: 64

paths:
  cache_dir: /mnt/data/caches
