apiVersion: v1
kind: Pod
metadata:
  name: as-jet-train-pod
spec:
  restartPolicy: Never
  volumes:
    - name: as-train-pvc
      persistentVolumeClaim:
        claimName: as-jet-training-pvc

  initContainers:
  - name: setup-env
    image: python:3.10-slim
    command:
      - /bin/bash
      - -c
      - |
        set -ex
        apt-get update && apt-get install -y \
          python3.10-venv python3.10-dev libffi-dev \
          gcc g++ curl git wget

        python3.10 -m venv /mnt/data/python-env
        source /mnt/data/python-env/bin/activate
        pip install --upgrade pip

        git clone https://github.com/ArjunS07/s25-fermilab-research /tmp/repo
        cp -r /tmp/repo/src /mnt/data/
        pip install -r /mnt/data/src/requirements.txt || true
    volumeMounts:
      - mountPath: /mnt/data
        name: as-train-pvc
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1"

  containers:
  - name: trainer
    image: python:3.10-slim
    command:
      - /bin/bash
      - -c
      - |
        source /mnt/data/python-env/bin/activate
        python /mnt/data/src/train.py --out_dir /mnt/data/output
    volumeMounts:
      - mountPath: /mnt/data
        name: as-train-pvc
    resources:
      limits:
        nvidia.com/gpu: 1
        memory: "16Gi"
        cpu: "4"
      requests:
        nvidia.com/gpu: 1
        memory: "8Gi"
        cpu: "2"
